#pragma once

#include "tkpint.h"

#if !defined(TKPWIN_BACKEND)
#define TKPWIN_BACKEND RGFW
#endif

typedef void tkpwin_t;

tkpwin_t* tkpwin_create(const char* name, u32 w, u32 h);
void tkpwin_close(tkpwin_t*);

boolean tkpwin_has_closed(tkpwin_t*);

void tkpwin_present(tkpwin_t*);

boolean tkpwin_pressed(tkpwin_t*, u8 key);

typedef enum {
	tkpwin_key_null = 0,
	tkpwin_escape = '\033',
	tkpwin_backtick = '`',
	tkpwin_0 = '0',
	tkpwin_1 = '1',
	tkpwin_2 = '2',
	tkpwin_3 = '3',
	tkpwin_4 = '4',
	tkpwin_5 = '5',
	tkpwin_6 = '6',
	tkpwin_7 = '7',
	tkpwin_8 = '8',
	tkpwin_9 = '9',
	tkpwin_minus = '-',
	tkpwin_equals = '=',
	tkpwin_backSpace = '\b',
	tkpwin_tab = '\t',
	tkpwin_space = ' ',
	tkpwin_A = 'a',
	tkpwin_B = 'b',
	tkpwin_C = 'c',
	tkpwin_D = 'd',
	tkpwin_E = 'e',
	tkpwin_F = 'f',
	tkpwin_G = 'g',
	tkpwin_H = 'h',
	tkpwin_I = 'i',
	tkpwin_J = 'j',
	tkpwin_K = 'k',
	tkpwin_L = 'l',
	tkpwin_M = 'm',
	tkpwin_N = 'n',
	tkpwin_O = 'o',
	tkpwin_P = 'p',
	tkpwin_Q = 'q',
	tkpwin_R = 'r',
	tkpwin_S = 's',
	tkpwin_T = 't',
	tkpwin_U = 'u',
	tkpwin_V = 'v',
	tkpwin_W = 'w',
	tkpwin_X = 'x',
	tkpwin_Y = 'y',
	tkpwin_Z = 'z',
	tkpwin_period = '.',
	tkpwin_comma = ',',
	tkpwin_slash = '/',
	tkpwin_bracket = '[',
    tkpwin_closeBracket = ']',
    tkpwin_semicolon = ';',
	tkpwin_apostrophe = '\'',
	tkpwin_backSlash = '\\',
	tkpwin_return = '\n',
	tkpwin_enter = '\n',
	tkpwin_delete = '\177', /* 127 */
	tkpwin_F1,
	tkpwin_F2,
	tkpwin_F3,
	tkpwin_F4,
	tkpwin_F5,
	tkpwin_F6,
	tkpwin_F7,
	tkpwin_F8,
	tkpwin_F9,
	tkpwin_F10,
	tkpwin_F11,
	tkpwin_F12,
    tkpwin_F13,
    tkpwin_F14,
    tkpwin_F15,
    tkpwin_F16,
    tkpwin_F17,
    tkpwin_F18,
    tkpwin_F19,
    tkpwin_F20,
    tkpwin_F21,
    tkpwin_F22,
    tkpwin_F23,
    tkpwin_F24,
    tkpwin_F25,
	tkpwin_caps_lock,
	tkpwin_left_shift,
	tkpwin_left_control,
	tkpwin_left_alt,
	tkpwin_left_super,
	tkpwin_right_shift,
	tkpwin_right_control,
	tkpwin_right_alt,
	tkpwin_right_super,
	tkpwin_up,
	tkpwin_down,
	tkpwin_left,
	tkpwin_right,
	tkpwin_insert,
	tkpwin_menu,
	tkpwin_end,
	tkpwin_home,
	tkpwin_page_up,
	tkpwin_page_down,
	tkpwin_num_lock,
	tkpwin_np_slash,
	tkpwin_np_multiply,
	tkpwin_np_plus,
	tkpwin_np_minus,
	tkpwin_np_equal,
	tkpwin_np1,
	tkpwin_np2,
	tkpwin_np3,
	tkpwin_np4,
	tkpwin_np5,
	tkpwin_np6,
	tkpwin_np7,
	tkpwin_np8,
	tkpwin_np9,
	tkpwin_np0,
	tkpwin_np_period,
	tkpwin_np_return,
	tkpwin_scroll_lock,
    tkpwin_print_screen,
    tkpwin_pause,
	tkpwin_world1,
    tkpwin_world2,
    tkpwin_keyLast = 256
} tkpwin_key;
